export const projects = [
    {
        name: 'Url Shortener',
        tags: ['React', 'Sass', 'HTML', 'CSS', 'Axios', 'Javascript'],
        description: 'This is a pure frontend url shortener app. It uses the shrtcode API to shorten the urls. It also has a copy to clipboard functionality.',
        demoLink: 'https://phenomenal-vacherin-b70024.netlify.app/',
        githubLink: 'https://github.com/Robertron624/url-shortening-app',
        image: '/images/projects/url-shortenning-app.png',
    },
    {
        name: 'Tip Calculator',
        tags: ['React', 'Sass', 'HTML', 'CSS', 'HTML', 'Javascript'],
        description: 'This is a tip calculator app for you to use when you go to a restaurant with your friends',
        demoLink: 'https://gleeful-jelly-a5a2e7.netlify.app/',
        githubLink: 'https://github.com/Robertron624/tip-calculator-app',
        image: '/images/projects/tip-calculator-app.png',
    },
    {
        name: 'Rock Paper Scissors',
        tags: ['React', 'TailwindCSS', 'DaisyUI', 'HTML', 'Typescript', 'Zustand'],
        description: 'This is a rock paper scissors game. You can play against the computer. It saves the score in the local storage.',
        demoLink: 'https://melodic-zabaione-4cfebe.netlify.app/',
        githubLink: 'https://github.com/Robertron624/rock-paper-scissors',
        image: '/images/projects/rock-paper-scissors.png',
    },
    {
        name: 'IP Address Tracker',
        tags: ['React', 'Sass', 'Leaflet', 'React Leaflet', 'Typescript', 'Axios', 'Ipify API'],
        description: 'This is an IP Address Tracker app. You can search for an IP Address and it will show you the location in the map. By default it shows your IP Address.',
        demoLink: 'https://effortless-daffodil-a04cfc.netlify.app/',
        githubLink: 'https://github.com/Robertron624/ip-address-tracker',
        image: '/images/projects/ip-address-tracker.png',
    },
    {
        name: 'Interactive comments',
        tags: ['React', 'NextJs', 'TailwindCSS', 'DaisyUI', 'HTML', 'CSS', 'Axios', 'Typescript'],
        description: 'This is an interactive comments app. You can add comments, reply to comments, like comments, and like replies.',
        demoLink: 'https://melodic-lamington-1297e9.netlify.app/',
        githubLink: 'https://github.com/Robertron624/interactive-comments',
        image: '/images/projects/interactive-comments.png',
    },
    {
        name: 'Countries Details',
        tags: ['React', 'Sass', 'HTML', 'CSS', 'Axios', 'Typescript'],
        description: 'This is a countries details app. You can search for a country and it will show you the details of that country in a card. It also has a dark mode. It uses the rest countries API.',
        demoLink: 'https://stunning-profiterole-b75426.netlify.app/',
        githubLink: 'https://github.com/Robertron624/rest-countries-details',
        image: '/images/projects/countries-details.png',
    },
    {
        name: 'Image Uploader',
        tags: ['React', 'Sass', 'HTML', 'CSS', 'Axios', 'Typescript', 'Multer', 'MongoDB', 'Mongoose', 'Express', 'Node.js'],
        description: 'This is a fullstack image uploader app. You can upload images and it will show you the images in a card. There is also a frontend only version that uses imgDBB to store the images.',
        demoLink: 'https://robert-image-uploader.netlify.app/',
        githubLink: 'https://github.com/Robertron624/image-uploader-fullstack',
        image: '/images/projects/image-uploader.png',
    },
    {
        name: 'Country Quiz',
        tags: ['React', 'Sass', 'HTML', 'CSS', 'Axios', 'Typescript'],
        description: 'This is a country quiz app. You can answer questions about countries and test your geography knowledge. It uses the rest countries API.',
        demoLink: 'https://country-quiz-react-axios.netlify.app/',
        githubLink: 'https://github.com/Robertron624/country-quiz',
        image: '/images/projects/country-quiz.png',
    },
    {
        name: 'Product Details Page',
        tags: ['React', 'HTML', 'CSS', 'Axios', 'Typescript', 'NextJs', 'TailwindCSS', 'MaterialUI'],
        description: 'This is a product details page. It shows you the details of a product, you can add it to a minicart and change its quantity.',
        demoLink: 'https://robert-product-details-page.netlify.app/',
        githubLink: 'https://github.com/Robertron624/ecommerce-product-page',
        image: '/images/projects/ecommerce-pdp.png',
    }
];